# Generated by Django 4.2.1 on 2023-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EnrollmentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korisnici',
            name='role',
            field=models.CharField(choices=[('student', 'STUDENT'), ('administrator', 'ADMINISTRATOR'), ('profesor', 'PROFESOR')], max_length=20),
        ),
        migrations.AlterField(
            model_name='korisnici',
            name='status',
            field=models.CharField(choices=[('none', 'NONE'), ('redovan', 'REDOVAN'), ('izvanredan', 'IZVANREDAN')], max_length=20),
        ),
    ]
