# Generated by Django 4.2.1 on 2023-05-22 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnrollmentApp', '0004_alter_korisnici_role_alter_korisnici_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predmeti',
            old_name='nositelj',
            new_name='nositelj_id',
        ),
    ]
