# Generated by Django 4.2.1 on 2023-05-22 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EnrollmentApp', '0005_rename_nositelj_predmeti_nositelj_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='predmeti',
            old_name='nositelj_id',
            new_name='nositelj',
        ),
    ]
