# Generated by Django 4.2.1 on 2023-05-23 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EnrollmentApp', '0006_rename_nositelj_id_predmeti_nositelj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predmeti',
            name='nositelj',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
